services:
  feedbackservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
 
       # ConnectionStrings__DefaultConnection:"Server=sqlserver;Database=FeedbackPlatformDb;User Id=sa;Password=GeoParola2025!;TrustServerCertificate=True;"
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6001:8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  userservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=UserDb;User Id=sa;Password=GeoParola2025!;TrustServerCertificate=True;Encrypt=False;
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6002:8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
 
  sqlserver:
    ports:
      - "1414:1433"
    environment:
      SA_PASSWORD: "GeoParola2025!"
      ACCEPT_EULA: "Y"